#!/bin/bash

ttfpath=$1
target=$2

echo "converting ttf font $ttfpath to pbf at $target"

docker create -it --name fontnik gnostrenoff/fontnik build-glyphs /font.ttf /target
docker cp $ttfpath fontnik:/font.ttf
docker start -a fontnik
docker cp fontnik:/target/. $target
